version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/churchmeet

 mysqldb:
  image: mysql:5.7
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD:MyS@lr00tdb
  - MYSQL_DATABASE:churchmeet
  volumes:
  - ../db/churchmeet/mysql:/var/lib/mysql
  - ../db/churchmeet/mysql_config:/etc/mysql
